api = "0.4"

[buildpack]
  homepage = "https://github.com/paketo-buildpacks/go-build"
  id = "paketo-buildpacks/go-build"
  name = "Paketo Go Build Buildpack"

[metadata]
  include-files = ["bin/build", "bin/detect", "bin/run", "buildpack.toml"]
  pre-package = "./scripts/build.sh"

[[stacks]]
  id = "io.buildpacks.stacks.bionic"

[[stacks]]
  id = "io.paketo.stacks.tiny"

[[stacks]]
  id = "org.cloudfoundry.stacks.cflinuxfs3"
