pull_request_rules:
  - name: Auto merge pull requests from github-actions bot
    conditions:
      - author=github-actions[bot]
      # TODO: Fill in these conditions when they are finalized
      # - status-success=Unit Tests
      # - status-success=Integration Tests
    actions:
      merge:
        strict: true
        method: rebase
      delete_head_branch: {}
