# This workflow triggers on a published release event.
# Requires the following secrets:
# - LANGUAGE_FAMILY_REPO -> the full name of the repo to send the dispatch to (eg. paketo-buildpacks/nodejs)
# - PAKETO_BOT_GITHUB_TOKEN -> a token with permissions to send the dispatch to the language family repo

name: Send Dependency Update Dispatch

on:
  release:
    types: [published]

jobs:

  dispatch:
    runs-on: ubuntu-latest
    name: Send Dispatch
    steps:

    # Parses the release event JSON and fetches the details that make up a dependency update.
    # Dependency update details are provided as outputs.
    - name: Parse Release Dependency
      id: dependency
      uses: paketo-buildpacks/github-config/actions/dependency/parse@master
      with:
        token: ${{ secrets.PAKETO_BOT_GITHUB_TOKEN }}

    # Generic repository dispatch sender.
    - name: Send Repository Dispatch
      uses: paketo-buildpacks/github-config/actions/dispatch@master
      with:
        repos: ${{ secrets.LANGUAGE_FAMILY_REPO }}
        token: ${{ secrets.PAKETO_BOT_GITHUB_TOKEN }}
        event: dependency-update
        payload: |
          {
            "strategy": "replace",
            "dependency": {
              "id": "${{ steps.dependency.outputs.id }}",
              "sha256": "${{ steps.dependency.outputs.sha256 }}",
              "source": "${{ steps.dependency.outputs.source }}",
              "source_sha256": "${{ steps.dependency.outputs.source_sha256 }}",
              "stacks": ${{ steps.dependency.outputs.stacks }},
              "uri": "${{ steps.dependency.outputs.uri }}",
              "version": "${{ steps.dependency.outputs.version }}"
            }
          }
