# This workflow notifies language families on release of impl cnbs
# Requires the following:
# - secret PAKETO_BOT_GITHUB_TOKEN -> token with permissions to send dispatch to language family repos
# - file .github/language-family-membership listing target <org>/<repo> per line

name: Send Dependency Update Dispatch

on:
  release:
    types: [published]

jobs:

  dispatch:
    runs-on: ubuntu-latest
    name: Send Dispatch
    steps:

    - name: Check out
      uses: actions/checkout@v2

    - name: List enrolled language families
      id: language-families
      run : |
        if [ ! -f .github/language-family-membership ]; then
          echo "requires line record file .github/language-family-membership"
          exit 1
        fi
        list=$(awk -vORS=, '{print}' .github/language-family-membership | sed 's#,$#\n#')
        echo "::set-output name=list::$list"

    - name: Parse ID and Version
      id: dependency
      run: |
        echo "::set-output name=id::$(jq -r .repository.full_name ${{ github.event_path }})"
        echo "::set-output name=version::$(jq -r .release.tag_name ${{ github.event_path }} | sed 's/^v//')"

    # Generic repository dispatch sender.
    - name: Send Repository Dispatch
      uses: paketo-buildpacks/github-config/actions/dispatch@main
      with:
        repos: ${{ steps.language-families.outputs.list }}
        token: ${{ secrets.PAKETO_BOT_GITHUB_TOKEN }}
        event: dependency-update
        payload: |
          {
            "strategy": "replace",
            "dependency": {
              "id": "${{ steps.dependency.outputs.id }}",
              "version": "${{ steps.dependency.outputs.version }}"
            }
          }
